### ISSUE TITLE
Ruby 2.1

### ISSUE THREAD

**Issue by lordotter** [RCRM/redmine_people#3]
In Debian Jessie, the new upcoming release of Debian, there is Ruby 2.1 and Rails 4.1

I want to install it with that command, but there is only this exception. Can you please add a patch for this?

```bash
$ bundle exec rake redmine:plugins NAME=redmine_people RAILS_ENV=production
(in /usr/share/redmine)
rake aborted!
ArgumentError: Unknown key: :conditions. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :remote, :dependent, :primary_key, :inverse_of, :order, :as
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/hash/keys.rb:71:in `block in assert_valid_keys'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/hash/keys.rb:69:in `each_key'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/core_ext/hash/keys.rb:69:in `assert_valid_keys'
/var/lib/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations/builder/association.rb:81:in `validate_options'
/var/lib/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations/builder/association.rb:61:in `initialize'
/var/lib/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations/builder/association.rb:46:in `new'
/var/lib/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations/builder/association.rb:46:in `create_builder'
/var/lib/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations/builder/association.rb:35:in `build'
/var/lib/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations.rb:1320:in `has_one'
/usr/share/redmine/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:14:in `block in included'
/usr/share/redmine/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:12:in `class_eval'
/usr/share/redmine/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:12:in `included'
/usr/share/redmine/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:42:in `include'
/usr/share/redmine/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:42:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:348:in `require_or_load'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:307:in `depend_on'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:225:in `require_dependency'
/usr/share/redmine/plugins/redmine_people/lib/redmine_people.rb:6:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:438:in `instance_exec'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:438:in `block in make_lambda'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:184:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:184:in `block in simple'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:185:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:185:in `block in simple'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:185:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:185:in `block in simple'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:185:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:185:in `block in simple'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
/var/lib/gems/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/lib/gems/2.1.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
/var/lib/gems/2.1.0/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/usr/share/redmine/lib/tasks/redmine.rake:52:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by knvmmohan** [comment]
I got the same issue with user_patch.rb

[redmine@NXCD005 redmine-3.0.2]$ rake redmine:plugins:migrate RAILS_ENV=production                                                  rake aborted!
ArgumentError: Unknown key: :conditions. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :dependent, :primary_key, :inverse_of, :required, :as, :foreign_type
/home/redmine/redmine-3.0.2/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:14:in `block in included'
/home/redmine/redmine-3.0.2/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:12:in `class_eval'
/home/redmine/redmine-3.0.2/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:12:in `included'
/home/redmine/redmine-3.0.2/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:42:in `include'
/home/redmine/redmine-3.0.2/plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:42:in `<top (required)>'
/home/redmine/redmine-3.0.2/plugins/redmine_people/lib/redmine_people.rb:6:in `block in <top (required)>'
/home/redmine/redmine-3.0.2/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by sergeyz** [comment]
Hi! Its not supported yet, please follow http://www.redminecrm.com/projects/people/pages/1
